const n = "_button_1eq8n_1", _ = "_sizeXS_1eq8n_27", e = "_sizeS_1eq8n_35", o = "_sizeL_1eq8n_43", i = "_onlyIcon_1eq8n_51", t = "_icon_1eq8n_64", c = "_viewClear_1eq8n_69", s = "_viewGhost_1eq8n_77", a = "_viewPrimary_1eq8n_85", q = "_viewSecondary_1eq8n_93", l = "_disabled_1eq8n_107", d = "_loading_1eq8n_107", r = "_content_1eq8n_117", v = "_icon__Left_1eq8n_132", w = "_icon__Right_1eq8n_135", y = {
  button: n,
  sizeXS: _,
  sizeS: e,
  sizeL: o,
  onlyIcon: i,
  icon: t,
  viewClear: c,
  viewGhost: s,
  viewPrimary: a,
  viewSecondary: q,
  disabled: l,
  loading: d,
  content: r,
  icon__Left: v,
  icon__Right: w
};
export {
  n as button,
  r as content,
  y as default,
  l as disabled,
  t as icon,
  v as icon__Left,
  w as icon__Right,
  d as loading,
  i as onlyIcon,
  o as sizeL,
  e as sizeS,
  _ as sizeXS,
  c as viewClear,
  s as viewGhost,
  a as viewPrimary,
  q as viewSecondary
};
