const _ = "_card_13up2_1", a = "_card__NoShadow_13up2_9", c = "_card__FormSquare_13up2_12", r = "_card__SpaceVerticalXS_13up2_15", e = "_card__SpaceVerticalS_13up2_19", o = "_card__SpaceVerticalM_13up2_23", t = "_card__SpaceVerticalL_13up2_27", p = "_card__SpaceVerticalXL_13up2_31", S = "_card__SpaceVertical2XL_13up2_35", d = "_card__SpaceVertical3XL_13up2_39", l = "_card__SpaceVertical4XL_13up2_43", i = "_card__SpaceVertical5XL_13up2_47", n = "_card__SpaceHorizontalXS_13up2_51", L = "_card__SpaceHorizontalS_13up2_55", X = "_card__SpaceHorizontalM_13up2_59", z = "_card__SpaceHorizontalL_13up2_63", H = "_card__SpaceHorizontalXL_13up2_67", V = "_card__SpaceHorizontal2XL_13up2_71", s = "_card__SpaceHorizontal3XL_13up2_75", u = "_card__SpaceHorizontal4XL_13up2_79", M = "_card__SpaceHorizontal5XL_13up2_83", h = {
  card: _,
  card__NoShadow: a,
  card__FormSquare: c,
  card__SpaceVerticalXS: r,
  card__SpaceVerticalS: e,
  card__SpaceVerticalM: o,
  card__SpaceVerticalL: t,
  card__SpaceVerticalXL: p,
  card__SpaceVertical2XL: S,
  card__SpaceVertical3XL: d,
  card__SpaceVertical4XL: l,
  card__SpaceVertical5XL: i,
  card__SpaceHorizontalXS: n,
  card__SpaceHorizontalS: L,
  card__SpaceHorizontalM: X,
  card__SpaceHorizontalL: z,
  card__SpaceHorizontalXL: H,
  card__SpaceHorizontal2XL: V,
  card__SpaceHorizontal3XL: s,
  card__SpaceHorizontal4XL: u,
  card__SpaceHorizontal5XL: M
};
export {
  _ as card,
  c as card__FormSquare,
  a as card__NoShadow,
  V as card__SpaceHorizontal2XL,
  s as card__SpaceHorizontal3XL,
  u as card__SpaceHorizontal4XL,
  M as card__SpaceHorizontal5XL,
  z as card__SpaceHorizontalL,
  X as card__SpaceHorizontalM,
  L as card__SpaceHorizontalS,
  H as card__SpaceHorizontalXL,
  n as card__SpaceHorizontalXS,
  S as card__SpaceVertical2XL,
  d as card__SpaceVertical3XL,
  l as card__SpaceVertical4XL,
  i as card__SpaceVertical5XL,
  t as card__SpaceVerticalL,
  o as card__SpaceVerticalM,
  e as card__SpaceVerticalS,
  p as card__SpaceVerticalXL,
  r as card__SpaceVerticalXS,
  h as default
};
