const _ = "_menu_18kdd_1", n = "_item_18kdd_1", l = "_link_18kdd_4", i = "_link__Active_18kdd_15", e = "_menu__Dark_18kdd_21", k = "_menu__Tooltip_18kdd_24", o = "_item__Active_18kdd_57", t = "_link__Collapsible_18kdd_92", d = "_link__Collapsed_18kdd_92", c = "_link_Title_18kdd_96", s = "_link_TitleWrapper_18kdd_97", p = "_link_Arrow_18kdd_100", a = "_link__Toggle_18kdd_103", r = "_link__ToggleOpen_18kdd_114", g = "_link_BadgeIconWrapper_18kdd_121", m = "_link_Icon_18kdd_126", T = "_link_DotBadge_18kdd_149", u = {
  menu: _,
  item: n,
  link: l,
  link__Active: i,
  menu__Dark: e,
  menu__Tooltip: k,
  item__Active: o,
  link__Collapsible: t,
  link__Collapsed: d,
  link_Title: c,
  link_TitleWrapper: s,
  link_Arrow: p,
  link__Toggle: a,
  link__ToggleOpen: r,
  link_BadgeIconWrapper: g,
  link_Icon: m,
  link_DotBadge: T
};
export {
  u as default,
  n as item,
  o as item__Active,
  l as link,
  p as link_Arrow,
  g as link_BadgeIconWrapper,
  T as link_DotBadge,
  m as link_Icon,
  c as link_Title,
  s as link_TitleWrapper,
  i as link__Active,
  d as link__Collapsed,
  t as link__Collapsible,
  a as link__Toggle,
  r as link__ToggleOpen,
  _ as menu,
  e as menu__Dark,
  k as menu__Tooltip
};
