const _ = "_badge_3sxct_1", t = "_badge__ViewFilled_3sxct_8", e = "_badge__StatusError_3sxct_11", s = "_badge__StatusSuccess_3sxct_14", a = "_badge__StatusNormal_3sxct_17", c = "_badge__StatusWarning_3sxct_20", o = "_badge__StatusSystem_3sxct_23", b = "_badge__ViewStroked_3sxct_27", d = "_count_3sxct_33", r = "_badge__SizeXS_3sxct_37", g = "_badge__SizeS_3sxct_44", S = "_badge__SizeM_3sxct_51", l = "_badge__SizeL_3sxct_55", n = "_badge__NotWrapper_3sxct_83", u = "_scrollNumber_Custom_3sxct_83", i = "_scrollNumber_3sxct_83", m = "_dot_3sxct_110", x = "_scrollNumber_Only_3sxct_135", N = "_scrollNumber_OnlyUnit_3sxct_143", z = {
  badge: _,
  badge__ViewFilled: t,
  badge__StatusError: e,
  badge__StatusSuccess: s,
  badge__StatusNormal: a,
  badge__StatusWarning: c,
  badge__StatusSystem: o,
  badge__ViewStroked: b,
  count: d,
  badge__SizeXS: r,
  badge__SizeS: g,
  badge__SizeM: S,
  badge__SizeL: l,
  badge__NotWrapper: n,
  scrollNumber_Custom: u,
  scrollNumber: i,
  dot: m,
  scrollNumber_Only: x,
  scrollNumber_OnlyUnit: N
};
export {
  _ as badge,
  n as badge__NotWrapper,
  l as badge__SizeL,
  S as badge__SizeM,
  g as badge__SizeS,
  r as badge__SizeXS,
  e as badge__StatusError,
  a as badge__StatusNormal,
  s as badge__StatusSuccess,
  o as badge__StatusSystem,
  c as badge__StatusWarning,
  t as badge__ViewFilled,
  b as badge__ViewStroked,
  d as count,
  z as default,
  m as dot,
  i as scrollNumber,
  u as scrollNumber_Custom,
  x as scrollNumber_Only,
  N as scrollNumber_OnlyUnit
};
