const _ = "_badge_jqtgo_1", t = "_badge__ViewFilled_jqtgo_8", e = "_badge__StatusSystem_jqtgo_11", o = "_badge__ViewStroked_jqtgo_14", a = "_count_jqtgo_20", s = "_badge__SizeXS_jqtgo_24", g = "_badge__SizeS_jqtgo_31", b = "_badge__SizeM_jqtgo_38", d = "_badge__SizeL_jqtgo_42", r = "_badge__StatusNormal_jqtgo_46", S = "_badge__StatusSuccess_jqtgo_51", c = "_badge__StatusError_jqtgo_56", l = "_badge__StatusWarning_jqtgo_61", n = "_badge__NotWrapper_jqtgo_70", u = "_scrollNumber_Custom_jqtgo_70", i = "_scrollNumber_jqtgo_70", m = "_dot_jqtgo_97", j = "_scrollNumber_Only_jqtgo_122", q = "_scrollNumber_OnlyUnit_jqtgo_130", N = {
  badge: _,
  badge__ViewFilled: t,
  badge__StatusSystem: e,
  badge__ViewStroked: o,
  count: a,
  badge__SizeXS: s,
  badge__SizeS: g,
  badge__SizeM: b,
  badge__SizeL: d,
  badge__StatusNormal: r,
  badge__StatusSuccess: S,
  badge__StatusError: c,
  badge__StatusWarning: l,
  badge__NotWrapper: n,
  scrollNumber_Custom: u,
  scrollNumber: i,
  dot: m,
  scrollNumber_Only: j,
  scrollNumber_OnlyUnit: q
};
export {
  _ as badge,
  n as badge__NotWrapper,
  d as badge__SizeL,
  b as badge__SizeM,
  g as badge__SizeS,
  s as badge__SizeXS,
  c as badge__StatusError,
  r as badge__StatusNormal,
  S as badge__StatusSuccess,
  e as badge__StatusSystem,
  l as badge__StatusWarning,
  t as badge__ViewFilled,
  o as badge__ViewStroked,
  a as count,
  N as default,
  m as dot,
  i as scrollNumber,
  u as scrollNumber_Custom,
  j as scrollNumber_Only,
  q as scrollNumber_OnlyUnit
};
